// Constants

export const FETCH_ALL_COIN_DATA = "FETCH_ALL_COIN_DATA";
export const SEARCH_COIN = "SEARCH_COIN";
export const FETCH_SEARCHED_COIN = "FETCH_SEARCHED_COIN";
export const IS_PENDING = "IS_PENDING";
export const FETCH_LINE_GRAPH_DATA = "FETCH_LINE_GRAPH_DATA";
export const SIGN_UP_MODAL = "SIGN_UP_MODAL";
export const SIGN_IN_MODAL = "SIGN_IN_MODAL";
export const FETCH_NEWS_DATA = "FETCH_NEWS_DATA";
export const SELECT_LINE_GRAPH_DAY = " SELECT_LINE_GRAPH_DAY";
export const SELECTED_LINK = "SELECTED_LINK";
export const GOOGLE_AUTH_TOKEN = "GOOGLE_AUTH_TOKEN";
export const MOBILE_NAV = "MOBILE_NAV";
